### ISSUE TITLE
Return a value from inside the callback

### ISSUE THREAD

**Issue by bfdykstra** [andyfleming/interval-promise#4] opened 2018-06-04 23:01 UTC
So I would like to return the value that is returned from the func promise resolution. I cannot seem to do this: 
```
const interval = require('./interval')

var resolveArray = function() {
  return new Promise(function(resolve) {
    setTimeout(function(){
      resolve({data: [1,2,3], status: 200})
    }, 500);
  }).then((data) => {
    console.log('value i want to return: ', data)
    return data
  })
  .catch(err => console.log('error: ', err))
}

function goFetchSomething() {
  const x = interval(async (iteration, stop) => {
    stop()
    // i want the results of resolve array to be returned from this function and to be available in the resulting promise chain
    return resolveArray()
      
  }, 1000, {stopOnError: false, iterations: 3}).then((intervalRes) => console.log('interval response: ', intervalRes))
 
}

goFetchSomething()
```

ideally, i'd see this `{data: [1,2,3], status: 200}` where i log the interval response

**Comment by andyfleming** [comment] 2018-06-06 05:53
Closing this as it's not a bug or feature request. I'll do my best to help though.

Not being able to resolve a value to the outer promise is something I overlooked in the initial design of the library. I may update it and bump it to a 2.0 version to make this easier. However, you can use an approach like below to achieve your desired behavior.

```js
const interval = require('interval-promise')

// You can shorten your mock function here by just using Promise.resolve
const resolveArray = () => Promise.resolve({data: [1,2,3], status: 200})

function goFetchSomething() {

  // Set up a variable to store the results once we successfully
  let finalResult

  // Also set a variable to track if the results were gotten
  let finalResultSet = false

  interval(async (iteration, stop) => {

    try {
      // Try to resolve the array
      const result = await resolveArray()

      // If it didn't throw an error, then it worked and we can store the results
      finalResult = result
      finalResultSet = true

      // (and stop the iterations)
      stop()
      
    } catch (err) {
        console.log(err)
    }
  }, 1000, {stopOnError: false, iterations: 3})
    .then(() => {
        if (finalResultSet) {
            console.log('interval response: ', finalResult)
        } else {
            console.log('No result was successfully recieved after 3 attempts')
        }
    })
 
}

goFetchSomething()
```

**Closed by andyfleming** 2018-06-06 05:53 UTC
Labels: question

**Comment by dwjohnston** [comment] 2019-04-05 02:30
@andyfleming  Just echoing a +1 that returning a value is what I want to be able to do.

**Comment by andyfleming** [comment] 2019-04-05 23:48
@dwjohnston Thanks for the feedback! This will be supported in v2.

**Comment by dwjohnston** [comment] 2019-04-07 23:23
@andyfleming  - If you're interested, here's how I've been using it to achieve this. 

```
//My wrapper function that uses interval-promise
async function startPolling(exitFn) {
    let finalResult; //This isn't nice, but it's a limit of the library. 
    const result = await interval(async (interval, stop) => {

        const doStop= await exitFn();
        if (doStop) {
            finalResult = doStop; 
           stop(); 
        } 
    }, POLL_RATE); 
    return finalResult; 
}
```

```
//Usage of the function
        await proof.requestProof(connection);

        await startPolling(async () => {
            const state = await proof.getState(); 
            if (state === StateType.RequestReceived) {
                console.log("recieved"); 
                return true; 
            }
            else {
                console.log(`the state is ${state}`)
                await proof.updateState();
                return false; 
            }
         }); 

        var proof_return = await proof.getProof(connection);
```

**Comment by andyfleming** [comment] 2019-04-14 04:51
Thanks for sharing @dwjohnston!

In interval-promise I have a similar function planned called `retry` that will work similarly. 👍
