### ISSUE TITLE
Correct import with typescript?

### ISSUE THREAD

**Issue by chriszrc** [andyfleming/interval-promise#6] opened 2018-06-12 15:50 UTC
I am not a typescript expert, but I tried all the typical ways one could import "interval" and none of them worked for me except:

```
const interval = require("interval-promise");
```

Ideally I'd like to stick with the es6 standard import, but I couldn't make it work. Is this possible?

**Comment by andyfleming** [comment] 2018-06-12 21:46
I'm using TypeScript version `2.7.2` and `interval-promise#1.2.0` using the following syntax successfully:

```typescript
import interval from "interval-promise";
```

**Comment by chriszrc** [comment] 2018-06-13 14:19
Yeah, I would've thought that that would work as well (I'm on the latest version of interval–promise and I was on typescript version 2.7.1 and upgraded to the latest there too (2.9.1)). But when I switched to the import syntax, I get the following error on the `await interval` line:

```
Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'interval-promise'' has no compatible call signatures.
```

code looks like this:

```typescript
let rate = 60 * 60 / 500 * 1000;

await interval(async (iterationNumber: number, stop: () => void) => {
  let json = await fetch(getApiUrl(iterationNumber)).then(res => res.json());

  for(let i=0; i<json.length; i++){
     ...//omitted
   }
  
  if (iterationNumber >= rows.length) {
     stop();
  }
}, rate);
```

This all works fine if I just switch the import back to a requires statement. Can you post what your tsconfig looks like?

**Comment by andyfleming** [comment] 2018-06-14 04:04
Your code looks fine in WebStorm for me and also compiles. I tested in the `express-typescript-starter` template from Microsoft, using TypeScript 2.7.2.

```typescript
import interval from "interval-promise";

const getApiUrl = (num: number) => "http://www.example.com/";
const rate = 60 * 60 / 500 * 1000;
const rows: any = [];

(async () => {
    await interval(async (iterationNumber: number, stop: () => void) => {
        const json = await fetch(getApiUrl(iterationNumber)).then(res => res.json());

        for (let i = 0; i < json.length; i++) {
            // ...omitted
        }

        if (iterationNumber >= rows.length) {
            stop();
        }
    }, rate);
})();
```

`tsconfig.json`

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by andyfleming** [comment] 2018-06-14 04:30
Maybe double-check the version in your `package.json`, delete your `node_modules` directory and run a fresh `npm install`?

Also, I'm going to close this issue for now since I can't reproduce a bug in the typescript definition directly. (I'll reopen it if it does turn out to be that). 

Feel free to keep commenting on here though and I'll do my best to help. 😃

**Closed** 2018-06-14 04:30 UTC
Labels: question
